# Abgerundete Ecken (Radius in Pixeln)
corner-radius = 10;

# Schatten aktivieren (nur einmal nötig)
shadow = true;

# Optional: Schatten-Radius (macht den Schatten weicher)
shadow-radius = 12;

animations = true;
animation-stiffness = 3000.0;   # Standard 300.0
animation-window-mass = 2.0;    # Standard 2.0
animation-clamping = true;
animation-for-open-window = "zoom";
